specVersion: 1.0.0
name: kusama-starter
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: index integritee solo node
repository: 'https://github.com/subquery/kusama-subql-starters'
schema:
  file: ./schema.graphql
network:
  chainId: '0xf195ef30c646663a24a3164b307521174a86f437c586397a43183c736a8383c1'
  endpoint: 'wss://api.solo.integritee.io'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
